### ISSUE TITLE
Guzzle 6.x compatibility

### ISSUE THREAD

**Issue by sandervanhooft** [freshheads/FHPostcodeAPIClient#13]
@owner

The FHPostcodeAPIClient seems not yet compatible with Guzzle ^6.*.

Any plans for updating?

**Comment by jvandesande** [comment]
We would like to use [HTTP Plug](http://httplug.io/) in the next major version (see #14).

**Comment by sandervanhooft** [comment]
Thanks for following up!

@jvandesande Thanks for pointing me to HTTPlug, didn't know about that one. Seems practical. The abstractions are nice for sure.

Sidenote: I'm not yet convinced it will replace Guzzle as the next best practice though. HTTPlug currently has only 264 Github stars. I haven't encountered it as a dependency in the major PHP frameworks as of yet.

I'll keep an eye out for the update.

Say hi to Bart from me!

Sander

**Comment by slokhorst** [comment]
This was fixed by #15.

**Comment by jvandesande** [comment]
This was solved in version 3 (https://github.com/freshheads/FHPostcodeAPIClient/releases/tag/3.0.0)
