### ISSUE TITLE
JSON_BIGINT_AS_STRING issue

### ISSUE THREAD

**Issue by bashilbers** [freshheads/FHPostcodeAPIClient#8]
Hi! Is the use of JSON_BIGINT_AS_STRING really needed? It is missing in some JSON modules (distribution specific). Ergo I am getting a `json_bigint_as_string not implemented` PHP warning and I use JSON-C version 0.11

**Comment by gnoesiboe** [comment]
Now that I look at it, it seems the API itself is returning strings instead of big integers. So it should be working without: `JSON_BIGINT_AS_STRING`. I will test this further this afternoon

**Comment by gnoesiboe** [comment]
FYI: https://github.com/freshheads/FHPostcodeAPIClient/pull/9
